CREATE TABLE IF NOT EXISTS log_roteiros(  
    id_exeo int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    req_message VARCHAR(500) NOT NULL,
    res_message VARCHAR(500) NOT NULL,
    dt_exeo TIMESTAMP NOT NULL
);
